config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get '/login' => 'sessions#new'#  Deixei comentário porque o "match" abaixo já resolveria..
  post 'login' => 'sessions#create'#  Deixei comentário porque o "match" abaixo já resolveria..
  delete 'logout' => 'sessions#destroy'#  Deixei comentário porque o "match" abaixo já resolveria..

  resources :categories do
    resources :items do
      resources :comments
    end
  end
  
  get 'signup'  => 'users#new'
  resources :users

  match ':controller(/:action(/:id))', :via => 'get'

  root 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :item

	validates :body, presence: true#, length: { minimum: 5 }  
 	validates :score, presence: true, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10}
	 	#, allow_nil:true
 
	# after_initialize / after_find => calculate_average
	after_create do
		item.calculate_average
	end

	after_destroy do
		item.calculate_average
	end

	after_update do
		item.calculate_average
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :set_category
  before_action :set_item#, only: [:create, :index, :show, :edit, :update, :destroy]

  before_action :set_comments
  before_action :set_comment, only: [:edit, :update, :destroy]

  # Only users can create comments.
  before_action :authorize

  def new
    @comment = Comment.new
  end

  def create
    # Find an Item of the comment (set_item)

    # Criar e salvar o comentário
    @comment = @item.comments.create(comment_params)
    redirect_to category_item_path(@category, @item)
  end

  def index
  end

  def edit
  end   

  def show
  end

  def update
    respond_to do |format|
      if @comment.update_attributes(comment_params)
        format.html { redirect_to category_item_path(@category, @item), notice: 'Comment was successfully updated.' }
        #format.json { head :no_content } NAO SEI PRA QUE SERVE ISSO!
      else
        format.html { render action: "edit" }
        #format.json { render json: @item.comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to category_item_path(@category, @item), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  
  def comment_params
    params.require(:comment).permit(:body, :score)
  end

  def set_category
    @category = Category.find(params[:category_id])
  end

  def set_item
    @item = Item.find(params[:item_id])
  end

  def set_comments
    @comments = @item.comments
  end

  def set_comment
    @comment = @item.comments.find(params[:id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for([@category, @item, @comment], html:{class:'form-horizontal'}, role:"form") do |f| %>
	<div class="form-group field">
		<%= f.label :score, class:"control-label" %> (0 - 10)
		<%= f.number_field :score, class:"form-control form_campo_color form_score" %> 
	</div>
	<div class="form-group field">
		<%= f.label :body, class:"control-label" %>
		<%= f.text_area :body, class:"form-control form_campo_color new_comment_box" %>
	</div>
	<div class="form-group actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/comments/_form_new.html.erb
<%= form_for([@category, @item, @comments.build], html:{class:'form-horizontal'}, role:"form") do |f| %>

  <div class="form-group field">
    <%= f.label :score, class:"control-label" %> (0 - 10)
    <%= f.number_field :score, class:"form-control form_campo_color form_score", placeholder:"0 - 10 only" %>
  </div>
  <div class="form-group field">
    <%= f.label :body, class:"control-label" %>
    <%= f.text_area :body, class:"form-control form_campo_color new_comment_box", placeholder:"Comment here" %>
  </div>
  <div class="form-group actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/_show.html.erb
<% if !@comments.any? %>
	<p>Be the first to comment!</p>
<% else %>
	<div class="bg-comments">
	<% @comments.each do |co| %>
		<div class="comments">
			<div class="container-fluid ">
				<div class="row-fluid">
					<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
						<strong>Score:</strong>
					</div>
					<div class="col-lg-11 col-md-11 col-sm-11 col-xs-11">
						<%= co.score %>
					</div>
				</div>
				<div class="row-fluid">
					<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
						<strong>Body:</strong>
					</div>
					<div class="col-lg-11 col-md-11 col-sm-11 col-xs-11">
						<%= co.body %>
					</div>
				</div>
			</div>
			<% if current_user != nil && current_user.admin? %>
			<div class="container-fluid btn-categories">
			<div class="row-fluid">
				<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
					<button type="button" class="btn-color-div btn_size">
						<%= link_to 'Edit', edit_category_item_comment_path(@category, @item, co) %>
					</button>
				</div>
				<div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
					<button type="button" class="btn-color-div btn_size">
						<%= link_to 'Destroy', category_item_comment_path(@category, @item, co), method: :delete, data: { confirm: 'Are you sure?' } %>
					</button>
				</div>				
			</div>
			</div>
			<% end %>
		</div>
	<% end %>
</div>
<% end %>

app/views/comments/edit.html.erb
<% provide(:title, 'Editing Comment') %>

<h3>
	<strong>
		Editing Comment
	</strong>
</h3>

<%= render 'form' %>

<button type="button" class="links_bottom_page">
	<%= link_to 'Back', category_item_path(@category, @item) %>
</button> 