config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get '/login' => 'sessions#new'#  Deixei comentário porque o "match" abaixo já resolveria..
  post 'login' => 'sessions#create'#  Deixei comentário porque o "match" abaixo já resolveria..
  delete 'logout' => 'sessions#destroy'#  Deixei comentário porque o "match" abaixo já resolveria..

  resources :categories do
    resources :items do
      resources :comments
    end
  end
  
  get 'signup'  => 'users#new'
  resources :users

  match ':controller(/:action(/:id))', :via => 'get'

  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
	has_many :comments, :dependent => :destroy # Sem este :dependent é impossível excluir itens com comentários
	belongs_to :category

	validates :category, presence: true
	validates :institution, presence: true
	validates :average, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10}, allow_nil:true

	def calculate_average 
		# create an array of v_scores, variable v_average and the v_sum.
		v_scores = Array.new
		v_average = nil
		v_sum = 0

		# Go through comments and store them at the array..
		self.comments.each do |c|
			v_scores.push(c.score)
		end

		puts "Array: #{v_scores}"

		# Sum the elements by Inject. It's the same of: v_scores.each do |value| v_sum += value
		v_sum = v_scores.inject(:+)

		puts "Sum of the elements: #{v_sum}"

		if v_scores.length < 1
			# v_average keep been nil
		else
			v_average = v_sum / v_scores.length
			puts "Average: #{v_average}"
		end

		# Save the average on the Itemself
		self.average = v_average
		self.save

		return self.average
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :set_category, only: [:create, :show, :edit, :update, :destroy]
  before_action :set_items, only: [:index, :show]
  before_action :set_item, only: [:edit, :update, :destroy, :show]
  before_action :set_comments, only: [:show, :edit, :update, :destroy]
  # Only admin can:
  before_action :authorize_admin, only: [:edit, :update, :destroy, :new, :create]
  # Everyone can see index and show
  before_action :authorize, except: [:index, :show]

  # GET /items
  # GET /items.json
  def index
    #@items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    #@error_message = params['format']
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    # Create and save the item
    @item = @category.items.create(item_params)

    redirect_to category_path(@category)
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update_attributes(item_params)
        format.html { redirect_to @category, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @category, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_category
      @category = Category.find(params[:category_id])
    end

    def set_items
      @items = @category.items
    end

    def set_item
      @item = @category.items.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:institution, :average, :category_id)
    end

    def set_comments
      @comments = @item.comments
    end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(([@category, @item]),html:{class:'form-horizontal', type:'form'}) do |f| %>

  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= f.label :category, class:"control-label col-lg-2 col-md-2 col-sm-2 col-xs-2" %>
    <label class="control-label col-lg-1 col-md-1 col-sm-1 col-xs-1">
      <%= @category.name %>
    </label>
  </div>
  <div class="form-group field">
    <%= f.label :institution, class:"control-label col-lg-2 col-md-2 col-sm-2 col-xs-2" %>
    <div class="col-lg-5 col-md-5 col-sm-5 col-xs-5">
      <%= f.text_field :institution, class:"form_campo_color" %>
    </div>
  </div>
  <div class="form-group actions">
    <div class="col-lg-offset-2 col-lg-10 col-md-offset-2 col-md-10 col-sm-offset-2 col-sm-10 col-xs-offset-2 col-xs-10">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/items/_form_new.html.erb
<%= form_for([@category, @category.items.build], html: {class:'form-horizontal'}, role:"form") do |f| %>
	<div class="form-group field">
		<%= f.label :'Add Institution:', class:"control-label" %>
		<%= f.text_field :institution, class:"form-control form_campo_color", placeholder:"Institution name" %>
	</div>
	<div class="form-group actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/items/_show.html.erb
<table class="table table-hover text-center" >
  <thead>
    <tr>
      <th colspan="4" class="text-center th_relative">
        <h3>
        <strong>
            <%= @category.name %> - Registered items:
        </strong>
        </h3>
        <% if current_user != nil && current_user.admin? %>
          <button type="button" class="links_bottom_th btn-color-head-table btn_size">
            <%= link_to 'Edit', edit_category_path(@category) %>
          </button>
        <% end %>
      </th>
    </tr>
    <tr>
      <th class="text-center">Institution</th>
      <th class="text-center">Average</th>
  		<% if current_user != nil && current_user.admin? %>
  	      <th colspan="1"></th>
  	      <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |it| %>
      <tr>
        <td>
          <%= link_to(it.institution, category_item_path(@category, it)) %>
        </td>
        <td>
  	      <% if it.average == nil %>
  	        <%= "--" %>
  	      <% else %>
  	        <%= it.average %>
  	      <% end %>
        </td>

        <% if current_user != nil && current_user.admin? %>
          <td>
            <button class="btn-color-table btn_size">
            <%= link_to('Edit', edit_category_item_path(@category, it)) %>
            </button>
          </td>
          <td>
            <button class="btn-color-table btn_size">
            <%= link_to('Destroy', category_item_path(@category, it), method: :delete, data: { confirm: 'Delete this item?' }) %>
            </button>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/edit.html.erb
<% provide(:title, 'Editing Item') %>

<h3>
	<strong>
		Editing Item
	</strong>
</h3>

<%= render 'form' %>

<button class="links_bottom_page" type="button">
	<%= link_to 'Back', category_item_path(@category, @item) %>
</button>

app/views/items/new.html.erb
<% provide(:title, 'Create Item') %>

<h3>
	<strong>
		New Item
	</strong>
</h3>

<%= render 'form' %>

<button class="links_bottom_page" type="button">
	<%= link_to 'Back', items_path %>
</button>

app/views/items/show.html.erb
<% provide(:title, 'Listing Items') %>

<p id="notice"><%= notice %></p>

<div class="row title_item">
  <div class="col-lg-4 col-md-3 col-sm-3 col-xs-3">
    <strong>Category:</strong>
    <%= @item.category.name  %>
  </div>  
  <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6">
    <strong>Institution:</strong>
    <%= @item.institution %>
    <% if current_user != nil && current_user.admin? %>
      <button type="button" class="btn-color-div btn-xs">
        <%= link_to 'Edit', edit_category_item_path(@category, @item) %> 
      </button>
    <% end %>
  </div>  
  <div class="col-lg-4 col-md-3 col-sm-3 col-xs-3">
    <strong>Average:</strong>
    <% if @item.average == nil %>
      <%= "--" %>
    <% else %>
      <%= @item.average %>
    <% end %>
  </div>
</div>

<h3 class="title">Comments</h3>
<%= render 'comments/show' %>

<% if current_user != nil %>
  <h2>Add comment</h2>
  <%= render'comments/form_new' %>
<% else %>
    <h3> Leave your comment! <%= link_to "Login", login_path %> </h3>
<% end %>

<button type="button" class="links_bottom_page btn_size">
  <%= link_to 'Back', category_path(@category) %>
</button>