config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'

  get 'welcome/about'

  get 'welcome/contact'

  get '/login' => 'sessions#new'#  Deixei comentário porque o "match" abaixo já resolveria..
  post 'login' => 'sessions#create'#  Deixei comentário porque o "match" abaixo já resolveria..
  delete 'logout' => 'sessions#destroy'#  Deixei comentário porque o "match" abaixo já resolveria..

  resources :categories do
    resources :items do
      resources :comments
    end
  end
  
  get 'signup'  => 'users#new'
  resources :users

  match ':controller(/:action(/:id))', :via => 'get'

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GDTO | <%= yield (:title) %> </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="page-header-fluid">
	<div class="container-fluid">
		<div class="row-fluid">
			<div class="logo">
				<p>
					<%= link_to image_tag('home1.jpg', class:"logo img-circle"), welcome_index_path %>
				</p>
			</div>
			<div class="main-menu col-lg-8 col-md-8 col-sm-8 col-xs-offset-2 col-xs-8">
				<nav class="navbar navbar-collapse">
					<!-- nav-justified doesn't show fine the nav in XS screen -->
					<ul class="nav nav-tabs nav-justified"> 
						<li class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
							<%= link_to(:Home, welcome_index_path, class:'effect_link_nav')%>
						</li>
						<li class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
							<%= link_to(:About, welcome_about_path, class:'effect_link_nav') %>
						</li>
						<li class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
							<%= link_to(:Contact, welcome_contact_path, class:'effect_link_nav')%>
						</li>
					<% if current_user != nil %>
						<li class="col-lg-2 col-md-2 col-sm-2 col-xs-6">
							<%= link_to(:Users, users_path, class:'effect_link_nav') %>
						</li>
					<% end %>
						<li class="dropdown text-center col-lg-4 col-md-4 col-sm-4">
							<%= link_to(:Categories, categories_path, class:'effect_link_nav') %>
							<ul class="submenu dropdown-menu ">
								<% @categories.each	do |c| %>
									<li class="">
										<%= link_to(c.name, c, class:'') %>
									</li>
								<% end %>
							</ul>
						</li>					
					</ul>
				</nav>
			</div>
			<div class="identification col-lg-2 col-md-2 col-sm-2 col-xs-2 text-right"">
				<% if current_user != nil %>
					<span id="user_identification">
						<span class="text-muted text-justify glyphicon glyphicon-user">
							<strong>
								<%= "#{current_user.email}" %> 
							</strong>
						</span>
						<br /> 
						<span class="btn btn-default btn-xs">
							<%= link_to "Log out", logout_path, method: "delete" %>
						</span>
					</span>
				<% else %>
					<span id="user_identification">
						<span class="btn btn-default btn-xs">
							<%= link_to "Login", login_path %> 
						</span>
						<br />
						<span class="btn btn-default btn-xs">
							<%= link_to "Sign up now!", new_user_path %>
						</span>
					</span>
				<% end %>
			</div>
		</div>
	</div>		
</div>

<div class="container-fluid content">
	<div class="row-fluid">
		<div class="col-lg-2 col-md-2 col-sm-2 col-xs-0">
			<div id="tecnologies" class="tecnologies">
				<div class="arrow_tecnologies"></div>
				<p align="center">Tecnologies:</p>
			</div>

			<div id="tecnologies_down" class="tecnologies_down">
				<ul>
					<% for i in @tecnologies.length.times %>
						<li> 
							<span class="glyphicon glyphicon-ok"></span>  
							<%= @tecnologies[i] %>
						</li>
					<% end %>
				</ul>
			</div>

		</div>
		<div class="col-lg-8 col-md-8 col-sm-9 col-xs-12 text-justify container content-intern">
			<%= yield %>
		</div>
		<div class="col-lg-2 col-md-2 col-sm-1 col-xs-0"></div>
	</div>
</div>

<div class="container-fluid footer text-center text-muted">
	<div class="row-fluid">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<span class="glyphicon glyphicon-copyright-mark"> 
				Developed by Moshe Ellovitch (Morré)
			</span>
		</div>
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
			<span class="glyphicon glyphicon-pencil"> 
				E-mail: moisesello@gmail.com
			</span>
		</div>
	</div>
</div>
</body>
</html>